### ISSUE TITLE
Data export

### ISSUE THREAD

**Issue by peva3** [tyge68/fitshow-treadmill#2]
Hey! Love this project and it worked right away with my treadmill. Do you have any built in mechanics to export/save data?

**Comment by tyge68** [comment]
Not yet, actually it store the data in the browser local storage, still thinking what would be best to export
maybe just allowing to copy/paste of the json would already do it, in my case I use it via the phone, but indeed editing the program steps is not as easy as on larger screen.

**Comment by tyge68** [comment]
@pmwoodward3  I just added import / export actions in the program editor top navigation, so the idea I guess is to save your program to your favorite cloud drive, so it can be shared among your devices.

Let me know if that help.
